trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndLint
  steps:
  - checkout: self
  
  - task: UseNode@1
    inputs:
      versionSpec: '14.x'
      checkLatest: true
      displayName: 'Install Node.js'

  - script: |
      npm install -g htmlhint
      htmlhint Nginx/**/*.html
    displayName: 'Run HTML Linting'

- job: DeployToVM
  steps:
  - checkout: self

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/Nginx
      Contents: '**'
      TargetFolder: $(Build.ArtifactStagingDirectory)/Nginx

  - task: SSH@0
    inputs:
      sshEndpoint: 'mytest'
      runOptions: 'inline'
      inline: |
        sudo apt-get update
        sudo apt-get install nginx -y
        sudo cp $(Build.ArtifactStagingDirectory)/Nginx/index.html /var/www/html/
        sudo systemctl restart nginx.service
      sshDebugEnabled: true
    displayName: 'Deploy HTML to VM'