
trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndLint
  steps:
  - checkout: self
  
  - task: UseNode@1
    inputs:
      versionSpec: '14.x'
      checkLatest: true
      displayName: 'Install Node.js'

  - script: |
      npm install -g htmlhint
      htmlhint Nginx/**/*.html
    displayName: 'Run HTML Linting'

- job: DeployToVM
  steps:
  - checkout: self

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: '**'
      TargetFolder: $(Build.ArtifactStagingDirectory)

  - task: SSH@0
    inputs:
      sshEndpoint: 'mytest'
      runOptions: 'inline'
      inline: |
        cd $(Build.ArtifactStagingDirectory)/Nginx
        chmod +x deploy_script.sh
        ./deploy_script.sh
      sshDebugEnabled: true
    displayName: 'Deploy HTML to VM'