trigger:
- main  # Adjust this to your desired branch

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToVM
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install Dependencies'
  
  - script: npx htmlhint index.html
    displayName: 'Lint HTML File'

  - script: echo 'Running tests...'
    displayName: 'Run Tests'
    
  - task: CopyFiles@2
    inputs:
      sourceFolder: './'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)/html'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/html'
      ArtifactName: 'html'
      publishLocation: 'Container'
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'html'  # Replace with your artifact name
      path: $(System.ArtifactsDirectory)

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'mytest'
      sourceFolder: '$(System.ArtifactsDirectory)/html'
      contents: '**/*.html'
      targetFolder: '/home/azure/'
  - task: SSH@0
    inputs:
      sshEndpoint: 'mytest'  # Replace with your SSH service connection name
      runOptions: 'inline'
      inline: 'sudo mv /home/azure/index.html /var/www/html/ && sudo systemctl restart nginx'
- job: RuntimeTest
  dependsOn: DeployToVM
  steps:
  - script: |
      # Run your runtime tests here (e.g., using curl, wget, or a testing framework)
      # For example, testing if the deployed page is accessible
      python -m pip install requests
      python -m pip install selenium
      python runtime_test.py
      # response=$(curl -s -o /dev/null -w "%{http_code}" http://20.55.105.192/)
      # if [ "$response" -eq "200" ]; then
      #   echo "Runtime test passed! Page is accessible."
      #   exit 0
      # else
      #   echo "Runtime test failed! Page returned HTTP status $response."
      #   exit 1
      # fi
    displayName: 'Run Runtime Test'