trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToVM
  steps:
  - checkout: self

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'webcontent'

  - task: SSH@0
    inputs:
      sshEndpoint: 'mytest'
      runOptions: 'inline'
      inline: |
        artifactDir="$(echo $(artifactDir) | tr -d '\r')"
        cd $artifactDir/Nginx
        chmod +x deploy_script.sh
        ./deploy_script.sh
      sshDebugEnabled: true
      failOnStdErr: true
      arguments: '-artifactDir "$(Build.ArtifactStagingDirectory)"'
